name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Build
        run: |
          yarn install --immutable
          cd lib
          yarn build
          cd ..
      # - name: Test
      #   run: |
      #     cd lib
      #     yarn test
      - name: Build docs
        run: |
          cd doc
          yarn build
          cd ..
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
  gh-release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "oss@samuelwall.co.uk"
          git config --global user.name "sjwall"
          yarn install --immutable
          cd doc
          yarn deploy
